import { Lead } from "@/types/lead";

export const INITIAL_DEMO_LEADS: Lead[] = [
  {
    id: "lead-1",
    companyName: "Acme Enterprise Solutions",
    contactName: "Sarah Jenkins",
    contactEmail: "s.jenkins@acme-ent.com",
    contactPhone: "+91 98765 43210",
    industry: "Fintech & Banking",
    dealValue: 1200000,
    stage: "negotiation",
    weightage: 75,
    expectedCloseDate: "2026-09-15",
    tags: ["Enterprise", "High Value", "Q3 Target"],
    owner: "Alex Mercer",
    notes: "Contract security review in final stages. Procurement approved pricing tier.",
    createdAt: "2026-08-10T09:30:00.000Z",
    updatedAt: "2026-08-30T16:45:00.000Z",
    journeyLogs: [
      {
        id: "log-1-1",
        timestamp: "2026-08-10T09:30:00.000Z",
        formattedDate: "Aug 10, 2026 at 09:30 AM",
        type: "lead_created",
        title: "Lead Discovered & Qualified",
        description: "Initial inbound lead inquiry for Enterprise SaaS license.",
        author: "Alex Mercer",
      },
      {
        id: "log-1-2",
        timestamp: "2026-08-14T11:15:00.000Z",
        formattedDate: "Aug 14, 2026 at 11:15 AM",
        type: "stage_change",
        title: "Stage Updated to Interest (10%)",
        description: "Initial discovery call completed. Client expressed strong interest in custom API integrations.",
        previousStage: undefined,
        newStage: "interest",
        author: "Alex Mercer",
      },
      {
        id: "log-1-3",
        timestamp: "2026-08-18T14:20:00.000Z",
        formattedDate: "Aug 18, 2026 at 02:20 PM",
        type: "stage_change",
        title: "Stage Updated to Share Proposal (25%)",
        description: "Delivered 3-year Enterprise proposal with tier 1 support package (₹12,00,000 ARR).",
        previousStage: "interest",
        newStage: "proposal",
        author: "Alex Mercer",
      },
      {
        id: "log-1-4",
        timestamp: "2026-08-23T15:00:00.000Z",
        formattedDate: "Aug 23, 2026 at 03:00 PM",
        type: "stage_change",
        title: "Stage Updated to Discussion with Team (50%)",
        description: "Presented technical Architecture deep-dive with CTO & Security Compliance team.",
        previousStage: "proposal",
        newStage: "discussion",
        author: "Alex Mercer",
      },
      {
        id: "log-1-5",
        timestamp: "2026-08-30T16:45:00.000Z",
        formattedDate: "Aug 30, 2026 at 04:45 PM",
        type: "stage_change",
        title: "Stage Updated to Pricing / Negotiations (75%)",
        description: "Redline contract feedback received. Negotiating SLA guarantees and payment terms.",
        previousStage: "discussion",
        newStage: "negotiation",
        author: "Alex Mercer",
      },
    ],
  },
  {
    id: "lead-2",
    companyName: "Nexus Health Systems",
    contactName: "Dr. Aris Thorne",
    contactEmail: "athorne@nexushealth.org",
    contactPhone: "+91 98123 45678",
    industry: "Healthcare & Biotech",
    dealValue: 850000,
    stage: "discussion",
    weightage: 50,
    expectedCloseDate: "2026-09-30",
    tags: ["HIPAA Compliant", "Hospital Network"],
    owner: "Elena Vance",
    notes: "Clinical team review in progress. Requested data processing addendum.",
    createdAt: "2026-08-15T10:00:00.000Z",
    updatedAt: "2026-08-28T14:10:00.000Z",
    journeyLogs: [
      {
        id: "log-2-1",
        timestamp: "2026-08-15T10:00:00.000Z",
        formattedDate: "Aug 15, 2026 at 10:00 AM",
        type: "lead_created",
        title: "Prospect Sourced",
        description: "Lead identified via B2B Medical Tech Conference.",
        author: "Elena Vance",
      },
      {
        id: "log-2-2",
        timestamp: "2026-08-20T13:30:00.000Z",
        formattedDate: "Aug 20, 2026 at 01:30 PM",
        type: "stage_change",
        title: "Stage Updated to Share Proposal (25%)",
        description: "Submitted customized Healthcare B2B proposal package (₹8,50,000).",
        previousStage: "interest",
        newStage: "proposal",
        author: "Elena Vance",
      },
      {
        id: "log-2-3",
        timestamp: "2026-08-28T14:10:00.000Z",
        formattedDate: "Aug 28, 2026 at 02:10 PM",
        type: "stage_change",
        title: "Stage Updated to Discussion with Team (50%)",
        description: "Scheduled committee review meeting with Chief Medical Information Officer.",
        previousStage: "proposal",
        newStage: "discussion",
        author: "Elena Vance",
      },
    ],
  },
  {
    id: "lead-3",
    companyName: "LogiTech Global Supply",
    contactName: "Marcus Vance",
    contactEmail: "marcus.v@logitechglobal.io",
    contactPhone: "+91 97111 22334",
    industry: "Logistics & Supply Chain",
    dealValue: 640000,
    stage: "proposal",
    weightage: 25,
    expectedCloseDate: "2026-10-15",
    tags: ["Supply Chain", "Automation"],
    owner: "David Miller",
    notes: "Proposal shared. Awaiting feedback from Operations Director.",
    createdAt: "2026-08-22T08:45:00.000Z",
    updatedAt: "2026-08-26T10:00:00.000Z",
    journeyLogs: [
      {
        id: "log-3-1",
        timestamp: "2026-08-22T08:45:00.000Z",
        formattedDate: "Aug 22, 2026 at 08:45 AM",
        type: "lead_created",
        title: "Lead Created",
        description: "Outreach response from LinkedIn prospecting campaign.",
        author: "David Miller",
      },
      {
        id: "log-3-2",
        timestamp: "2026-08-24T16:00:00.000Z",
        formattedDate: "Aug 24, 2026 at 04:00 PM",
        type: "stage_change",
        title: "Stage Updated to Interest (10%)",
        description: "Confirmed budget availability (₹6,00,000 - ₹7,00,000 range) and timeline.",
        previousStage: undefined,
        newStage: "interest",
        author: "David Miller",
      },
      {
        id: "log-3-3",
        timestamp: "2026-08-26T10:00:00.000Z",
        formattedDate: "Aug 26, 2026 at 10:00 AM",
        type: "stage_change",
        title: "Stage Updated to Share Proposal (25%)",
        description: "Sent comprehensive B2B workflow automation proposal.",
        previousStage: "interest",
        newStage: "proposal",
        author: "David Miller",
      },
    ],
  },
  {
    id: "lead-4",
    companyName: "Starlight Cyber Tech",
    contactName: "Samantha Reed",
    contactEmail: "sreed@starlightcyber.com",
    contactPhone: "+91 99887 66554",
    industry: "Cybersecurity",
    dealValue: 2100000,
    stage: "closure",
    weightage: 100,
    expectedCloseDate: "2026-08-29",
    tags: ["Key Account", "Closed Won"],
    owner: "Alex Mercer",
    notes: "Contract signed! Onboarding kicked off with CS manager.",
    createdAt: "2026-07-15T11:00:00.000Z",
    updatedAt: "2026-08-29T17:30:00.000Z",
    journeyLogs: [
      {
        id: "log-4-1",
        timestamp: "2026-07-15T11:00:00.000Z",
        formattedDate: "Jul 15, 2026 at 11:00 AM",
        type: "lead_created",
        title: "Lead Created",
        description: "Inbound request via B2B landing page.",
        author: "Alex Mercer",
      },
      {
        id: "log-4-2",
        timestamp: "2026-08-29T17:30:00.000Z",
        formattedDate: "Aug 29, 2026 at 05:30 PM",
        type: "stage_change",
        title: "Stage Updated to Closure (100%)",
        description: "Master Services Agreement executed! Deal weightage achieved 100%.",
        previousStage: "negotiation",
        newStage: "closure",
        author: "Alex Mercer",
      },
    ],
  },
  {
    id: "lead-5",
    companyName: "Vanguard Retail Group",
    contactName: "Robert Sterling",
    contactEmail: "r.sterling@vanguardretail.com",
    contactPhone: "+91 98989 00112",
    industry: "E-Commerce & Retail",
    dealValue: 450000,
    stage: "interest",
    weightage: 10,
    expectedCloseDate: "2026-11-01",
    tags: ["Mid-Market"],
    owner: "Elena Vance",
    notes: "Initial interest registered. Discovery meeting scheduled for next Tuesday.",
    createdAt: "2026-08-30T11:00:00.000Z",
    updatedAt: "2026-08-30T11:00:00.000Z",
    journeyLogs: [
      {
        id: "log-5-1",
        timestamp: "2026-08-30T11:00:00.000Z",
        formattedDate: "Aug 30, 2026 at 11:00 AM",
        type: "stage_change",
        title: "Stage Updated to Interest (10%)",
        description: "Lead engaged with email campaign and requested product brochure.",
        previousStage: undefined,
        newStage: "interest",
        author: "Elena Vance",
      },
    ],
  },
];
