import { ColdClient, ColdClientStatus, ColdStatusConfig, OutreachChannel } from "@/types/outreach";

export const COLD_STATUS_CONFIG: Record<ColdClientStatus, ColdStatusConfig> = {
  uncontacted: {
    id: "uncontacted",
    label: "Cold / Not Contacted",
    badgeBg: "bg-slate-100 dark:bg-slate-800/80",
    badgeText: "text-slate-700 dark:text-slate-300",
    borderColor: "border-slate-300 dark:border-slate-700",
    headerBg: "bg-slate-50 dark:bg-slate-900/50",
    iconName: "Snowflake",
    description: "Prospective corporate client identified but no touchpoint made yet.",
  },
  email_sent: {
    id: "email_sent",
    label: "1st Outreach Sent",
    badgeBg: "bg-blue-50 dark:bg-blue-950/60",
    badgeText: "text-blue-600 dark:text-blue-400",
    borderColor: "border-blue-400/40",
    headerBg: "bg-blue-50/50 dark:bg-blue-950/30",
    iconName: "Mail",
    description: "Initial introductory email or message delivered to the prospect.",
  },
  follow_up_1: {
    id: "follow_up_1",
    label: "Follow-Up #1 Sent",
    badgeBg: "bg-indigo-50 dark:bg-indigo-950/60",
    badgeText: "text-indigo-600 dark:text-indigo-400",
    borderColor: "border-indigo-400/40",
    headerBg: "bg-indigo-50/50 dark:bg-indigo-950/30",
    iconName: "RefreshCw",
    description: "First value-add follow-up or case study shared with prospect.",
  },
  follow_up_2: {
    id: "follow_up_2",
    label: "Follow-Up #2 Sent",
    badgeBg: "bg-purple-50 dark:bg-purple-950/60",
    badgeText: "text-purple-600 dark:text-purple-400",
    borderColor: "border-purple-400/40",
    headerBg: "bg-purple-50/50 dark:bg-purple-950/30",
    iconName: "Repeat",
    description: "Second follow-up or multi-channel nudge via LinkedIn/email.",
  },
  call_scheduled: {
    id: "call_scheduled",
    label: "Meeting / Call Booked",
    badgeBg: "bg-amber-50 dark:bg-amber-950/60",
    badgeText: "text-amber-600 dark:text-amber-400",
    borderColor: "border-amber-400/40",
    headerBg: "bg-amber-50/50 dark:bg-amber-950/30",
    iconName: "Calendar",
    description: "Discovery session or introductory video conference confirmed.",
  },
  replied_interested: {
    id: "replied_interested",
    label: "Interested / Engaged",
    badgeBg: "bg-emerald-50 dark:bg-emerald-950/60",
    badgeText: "text-emerald-600 dark:text-emerald-400",
    borderColor: "border-emerald-400/40",
    headerBg: "bg-emerald-50/50 dark:bg-emerald-950/30",
    iconName: "Sparkles",
    description: "Client responded positively and requested executive information.",
  },
  unresponsive: {
    id: "unresponsive",
    label: "Unresponsive / Snoozed",
    badgeBg: "bg-orange-50 dark:bg-orange-950/60",
    badgeText: "text-orange-600 dark:text-orange-400",
    borderColor: "border-orange-400/40",
    headerBg: "bg-orange-50/50 dark:bg-orange-950/30",
    iconName: "Clock",
    description: "No reply after multiple touches; scheduled to revisit next quarter.",
  },
  not_interested: {
    id: "not_interested",
    label: "Not a Fit / Passed",
    badgeBg: "bg-rose-50 dark:bg-rose-950/60",
    badgeText: "text-rose-600 dark:text-rose-400",
    borderColor: "border-rose-400/40",
    headerBg: "bg-rose-50/50 dark:bg-rose-950/30",
    iconName: "XCircle",
    description: "Client confirmed no current budget or requirement for leadership development.",
  },
  converted: {
    id: "converted",
    label: "Converted to Pipeline",
    badgeBg: "bg-cyan-50 dark:bg-cyan-950/60",
    badgeText: "text-cyan-600 dark:text-cyan-400",
    borderColor: "border-cyan-400/40",
    headerBg: "bg-cyan-50/50 dark:bg-cyan-950/30",
    iconName: "CheckCheck",
    description: "Successfully graduated into the active B2B CRM pipeline deals.",
  },
};

export const OUTREACH_CHANNELS: { id: OutreachChannel; label: string; icon: string }[] = [
  { id: "email", label: "Cold Email", icon: "Mail" },
  { id: "linkedin", label: "LinkedIn", icon: "Linkedin" },
  { id: "call", label: "Phone Call", icon: "Phone" },
  { id: "referral", label: "Referral", icon: "UserCheck" },
  { id: "event", label: "Event / Summit", icon: "Award" },
  { id: "other", label: "Other", icon: "Globe" },
];

export const OUTREACH_INDUSTRIES = [
  "Technology & SaaS",
  "BFSI & Fintech",
  "E-Commerce & Retail",
  "Healthcare & Pharma",
  "Manufacturing & Auto",
  "Consulting & Professional Services",
  "Telecommunications",
  "Media & Entertainment",
  "Education & EdTech",
  "Logistics & Supply Chain",
];

export const INITIAL_COLD_CLIENTS: ColdClient[] = [
  {
    id: "cold-101",
    companyName: "Swiggy (Bundl Technologies)",
    companyLogo: "https://logo.clearbit.com/swiggy.com",
    contactName: "Girish Menon",
    designation: "Head of Human Resources & Leadership",
    email: "girish.menon@swiggy.in",
    phone: "+91 98450 11223",
    linkedinUrl: "https://linkedin.com/in/girishmenon-hr",
    website: "https://swiggy.com",
    city: "Bengaluru",
    industry: "E-Commerce & Retail",
    targetProgram: "Executive Coaching",
    estimatedPotentialValue: 1200000,
    status: "email_sent",
    channel: "email",
    owner: "Karan",
    notes: "Targeting VP engineering & GM level leaders for executive presence & transition coaching.",
    touchpoints: [
      {
        id: "tp-1",
        timestamp: new Date(Date.now() - 3 * 86400000).toISOString(),
        formattedDate: "Sep 21, 2026, 11:30 AM",
        channel: "email",
        summary: "Sent customized B2B Executive Cold Outreach with leadership coaching ROI benchmarks.",
        author: "Karan",
      },
    ],
    lastContactDate: new Date(Date.now() - 3 * 86400000).toISOString().split("T")[0],
    nextFollowUpDate: new Date(Date.now() + 1 * 86400000).toISOString().split("T")[0],
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "cold-102",
    companyName: "Pine Labs",
    companyLogo: "https://logo.clearbit.com/pinelabs.com",
    contactName: "Anu Mathew",
    designation: "Chief People Officer",
    email: "anu.mathew@pinelabs.com",
    phone: "+91 98112 33445",
    linkedinUrl: "https://linkedin.com/in/anumathew-cpo",
    website: "https://pinelabs.com",
    city: "Noida / Gurugram",
    industry: "BFSI & Fintech",
    targetProgram: "L&D Transformation",
    estimatedPotentialValue: 1800000,
    status: "follow_up_1",
    channel: "linkedin",
    owner: "Pooja",
    notes: "Connected on LinkedIn, discussed capability building for mid-management to senior leaders.",
    touchpoints: [
      {
        id: "tp-2",
        timestamp: new Date(Date.now() - 7 * 86400000).toISOString(),
        formattedDate: "Sep 17, 2026, 03:15 PM",
        channel: "linkedin",
        summary: "Sent personalized connection note highlighting fintech leadership transformations.",
        author: "Pooja",
      },
      {
        id: "tp-3",
        timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
        formattedDate: "Sep 22, 2026, 04:45 PM",
        channel: "email",
        summary: "Shared L&D Architecture brochure and client transformation case study.",
        author: "Pooja",
      },
    ],
    lastContactDate: new Date(Date.now() - 2 * 86400000).toISOString().split("T")[0],
    nextFollowUpDate: new Date(Date.now() + 2 * 86400000).toISOString().split("T")[0],
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "cold-103",
    companyName: "Zepto (KiranaKart)",
    companyLogo: "https://logo.clearbit.com/zeptonow.com",
    contactName: "Vikramjeet Singh",
    designation: "VP Talent & Organizational Effectiveness",
    email: "vikramjeet.singh@zeptonow.com",
    phone: "+91 99201 44556",
    linkedinUrl: "https://linkedin.com/in/vikramjeetsingh",
    website: "https://zeptonow.com",
    city: "Mumbai",
    industry: "E-Commerce & Retail",
    targetProgram: "Assessments",
    estimatedPotentialValue: 950000,
    status: "call_scheduled",
    channel: "email",
    owner: "Karan",
    notes: "Discovery call scheduled to evaluate 360-degree leadership potential assessment tools.",
    touchpoints: [
      {
        id: "tp-4",
        timestamp: new Date(Date.now() - 4 * 86400000).toISOString(),
        formattedDate: "Sep 20, 2026, 02:00 PM",
        channel: "email",
        summary: "Cold pitch for Psychometric and 360 Assessment battery.",
        author: "Karan",
      },
      {
        id: "tp-5",
        timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
        formattedDate: "Sep 23, 2026, 05:20 PM",
        channel: "call",
        summary: "Brief phone call; agreed to 30-min Zoom demo next Tuesday.",
        author: "Karan",
      },
    ],
    lastContactDate: new Date(Date.now() - 1 * 86400000).toISOString().split("T")[0],
    nextFollowUpDate: new Date(Date.now() + 3 * 86400000).toISOString().split("T")[0],
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "cold-104",
    companyName: "Ather Energy",
    companyLogo: "https://logo.clearbit.com/atherenergy.com",
    contactName: "Sunitha Lal",
    designation: "Chief Human Resources Officer",
    email: "sunitha.lal@atherenergy.com",
    phone: "+91 97400 55667",
    linkedinUrl: "https://linkedin.com/in/sunithalal",
    website: "https://atherenergy.com",
    city: "Bengaluru",
    industry: "Manufacturing & Auto",
    targetProgram: "TASC Inhouse",
    estimatedPotentialValue: 1500000,
    status: "uncontacted",
    channel: "email",
    owner: "Admin",
    notes: "Identified rapid EV engineering scaling; potential fit for TASC in-house high potential academy.",
    touchpoints: [],
    nextFollowUpDate: new Date().toISOString().split("T")[0],
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "cold-105",
    companyName: "Razorpay",
    companyLogo: "https://logo.clearbit.com/razorpay.com",
    contactName: "Chitresh Sharma",
    designation: "Director - Leadership Development & Culture",
    email: "chitresh.sharma@razorpay.com",
    phone: "+91 99887 66554",
    linkedinUrl: "https://linkedin.com/in/chitreshsharma",
    website: "https://razorpay.com",
    city: "Bengaluru",
    industry: "BFSI & Fintech",
    targetProgram: "Executive Coaching",
    estimatedPotentialValue: 1600000,
    status: "replied_interested",
    channel: "linkedin",
    owner: "Karan",
    notes: "Chitresh replied wanting an overview of xMonks Master Coaches for Senior Directors.",
    touchpoints: [
      {
        id: "tp-6",
        timestamp: new Date(Date.now() - 5 * 86400000).toISOString(),
        formattedDate: "Sep 19, 2026, 10:00 AM",
        channel: "linkedin",
        summary: "InMail sent regarding Executive coaching roaster.",
        author: "Karan",
      },
      {
        id: "tp-7",
        timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
        formattedDate: "Sep 23, 2026, 01:10 PM",
        channel: "linkedin",
        summary: "Received reply: 'Send coach bios and commercial structure for 10-leader cohort.'",
        author: "Karan",
      },
    ],
    lastContactDate: new Date(Date.now() - 1 * 86400000).toISOString().split("T")[0],
    nextFollowUpDate: new Date().toISOString().split("T")[0],
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];
