import { ColdClient, ColdClientStatus, ColdStatusConfig, OutreachChannel } from "@/types/outreach";

export const COLD_STATUS_CONFIG: Record<ColdClientStatus, ColdStatusConfig> = {
  uncontacted: {
    id: "uncontacted",
    label: "Cold / Not Contacted",
    badgeBg: "bg-slate-100 dark:bg-slate-800/80",
    badgeText: "text-slate-700 dark:text-slate-300",
    borderColor: "border-slate-300 dark:border-slate-700",
    headerBg: "bg-slate-50 dark:bg-slate-900/50",
    iconName: "Snowflake",
    description: "Prospective corporate client identified but no touchpoint made yet.",
  },
  email_sent: {
    id: "email_sent",
    label: "1st Outreach Sent",
    badgeBg: "bg-blue-50 dark:bg-blue-950/60",
    badgeText: "text-blue-600 dark:text-blue-400",
    borderColor: "border-blue-400/40",
    headerBg: "bg-blue-50/50 dark:bg-blue-950/30",
    iconName: "Mail",
    description: "Initial introductory email or message delivered to the prospect.",
  },
  follow_up_1: {
    id: "follow_up_1",
    label: "Follow-Up #1 Sent",
    badgeBg: "bg-indigo-50 dark:bg-indigo-950/60",
    badgeText: "text-indigo-600 dark:text-indigo-400",
    borderColor: "border-indigo-400/40",
    headerBg: "bg-indigo-50/50 dark:bg-indigo-950/30",
    iconName: "RefreshCw",
    description: "First value-add follow-up or case study shared with prospect.",
  },
  follow_up_2: {
    id: "follow_up_2",
    label: "Follow-Up #2 Sent",
    badgeBg: "bg-purple-50 dark:bg-purple-950/60",
    badgeText: "text-purple-600 dark:text-purple-400",
    borderColor: "border-purple-400/40",
    headerBg: "bg-purple-50/50 dark:bg-purple-950/30",
    iconName: "Repeat",
    description: "Second follow-up or multi-channel nudge via LinkedIn/email.",
  },
  call_scheduled: {
    id: "call_scheduled",
    label: "Meeting / Call Booked",
    badgeBg: "bg-amber-50 dark:bg-amber-950/60",
    badgeText: "text-amber-600 dark:text-amber-400",
    borderColor: "border-amber-400/40",
    headerBg: "bg-amber-50/50 dark:bg-amber-950/30",
    iconName: "Calendar",
    description: "Discovery session or introductory video conference confirmed.",
  },
  replied_interested: {
    id: "replied_interested",
    label: "Interested / Engaged",
    badgeBg: "bg-emerald-50 dark:bg-emerald-950/60",
    badgeText: "text-emerald-600 dark:text-emerald-400",
    borderColor: "border-emerald-400/40",
    headerBg: "bg-emerald-50/50 dark:bg-emerald-950/30",
    iconName: "Sparkles",
    description: "Client responded positively and requested executive information.",
  },
  unresponsive: {
    id: "unresponsive",
    label: "Unresponsive / Snoozed",
    badgeBg: "bg-orange-50 dark:bg-orange-950/60",
    badgeText: "text-orange-600 dark:text-orange-400",
    borderColor: "border-orange-400/40",
    headerBg: "bg-orange-50/50 dark:bg-orange-950/30",
    iconName: "Clock",
    description: "No reply after multiple touches; scheduled to revisit next quarter.",
  },
  not_interested: {
    id: "not_interested",
    label: "Not a Fit / Passed",
    badgeBg: "bg-rose-50 dark:bg-rose-950/60",
    badgeText: "text-rose-600 dark:text-rose-400",
    borderColor: "border-rose-400/40",
    headerBg: "bg-rose-50/50 dark:bg-rose-950/30",
    iconName: "XCircle",
    description: "Client confirmed no current budget or requirement for leadership development.",
  },
  converted: {
    id: "converted",
    label: "Converted to Pipeline",
    badgeBg: "bg-cyan-50 dark:bg-cyan-950/60",
    badgeText: "text-cyan-600 dark:text-cyan-400",
    borderColor: "border-cyan-400/40",
    headerBg: "bg-cyan-50/50 dark:bg-cyan-950/30",
    iconName: "CheckCheck",
    description: "Successfully graduated into the active B2B CRM pipeline deals.",
  },
};

export const OUTREACH_CHANNELS: { id: OutreachChannel; label: string; icon: string }[] = [
  { id: "email", label: "Cold Email", icon: "Mail" },
  { id: "linkedin", label: "LinkedIn", icon: "Linkedin" },
  { id: "call", label: "Phone Call", icon: "Phone" },
  { id: "referral", label: "Referral", icon: "UserCheck" },
  { id: "event", label: "Event / Summit", icon: "Award" },
  { id: "other", label: "Other", icon: "Globe" },
];

export const OUTREACH_INDUSTRIES = [
  "Technology & SaaS",
  "BFSI & Fintech",
  "E-Commerce & Retail",
  "Healthcare & Pharma",
  "Manufacturing & Auto",
  "Consulting & Professional Services",
  "Telecommunications",
  "Media & Entertainment",
  "Education & EdTech",
  "Logistics & Supply Chain",
];

export const INITIAL_COLD_CLIENTS: ColdClient[] = [];
